name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Conftest
        uses: sentenz/actions/conftest@v1.0.2
        with:
          config-file: conftest.toml
