name: Regal
on:
  pull_request:
jobs:
  lint-rego:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Lint
        uses: sentenz/actions/regal@v1.0.2
        with:
          path: ./tests/policy
