name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Semgrep
        uses: sentenz/actions/semgrep@v1.0.2
        with:
          config: auto
          metrics: auto
